version: '3.8'

services:
  boot-app:
    image: sdeepak740/chatback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      environment:
        - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}






